/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_hundun_datarecovery_jni_DBParser */

#ifndef _Included_cn_hundun_datarecovery_jni_DBParser
#define _Included_cn_hundun_datarecovery_jni_DBParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_hundun_datarecovery_jni_DBParser
 * Method:    getSms
 * Signature: (Ljava/lang/String;Ljava/util/ArrayList;)V
 */
JNIEXPORT jobject JNICALL Java_cn_hundun_datarecovery_jni_DBParser_getSms
        (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_hundun_datarecovery_jni_DBParser
 * Method:    getCalls
 * Signature: (Ljava/lang/String;Ljava/util/ArrayList;)V
 */
JNIEXPORT jobject JNICALL Java_cn_hundun_datarecovery_jni_DBParser_getCalls
        (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif